apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: backend-git-repo
spec:
  params:
    - name: url
      value: 'https://github.com/openshiftninja/jboss-helloworld.git'
    - name: revision
      value: master
  type: git
